#!/usr/bin/env python3
"""
piCoreCDSP v2 — Upstream Status Dashboard Generator (roadmap §68, Gate 14)

Reads upstream/status.json, upstream/capabilities.yml, and probe results
to generate an up-to-date upstream/status.md dashboard.

Usage:
    python3 scripts/upstream_dashboard.py \\
        --status       upstream/status.json \\
        --capabilities upstream/capabilities.yml \\
        --probes       /tmp/probe-results-*.json \\
        --output       upstream/status.md
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml


def load_json(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        return {}
    return json.loads(p.read_text())


def load_yaml(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        return {}
    return yaml.safe_load(p.read_text()) or {}


def probe_status_icon(status: str) -> str:
    return {"PASS": "✅", "FAIL": "❌", "SKIP": "⏭", "ERROR": "⚠️"}.get(status, "⏳")


def collect_probe_results(probe_files: list[str]) -> dict[str, dict[str, str]]:
    """
    Returns: {branch: {capability_key: status_str}}
    """
    results: dict[str, dict[str, str]] = {}
    for pf in probe_files:
        data = load_json(pf)
        branch = data.get("branch", "unknown")
        results[branch] = {}
        for probe in data.get("probes", []):
            cap = probe.get("capability", "?")
            status = probe.get("status", "?")
            results[branch][cap] = status
    return results


def generate_dashboard(
    status: dict,
    capabilities: dict,
    probe_results: dict[str, dict[str, str]],
    generated_at: str,
) -> str:
    lines = [
        "<!-- upstream/status.md — auto-generated by upstream-sync.yml (roadmap §68). -->",
        "<!-- Do not edit manually. -->",
        "",
        "# piCoreCDSP v2 — Upstream Capability Status Dashboard",
        "",
        f"> **Auto-generated.** Last updated: `{generated_at}`",
        "",
        "This dashboard summarises what piCoreCDSP relies on from each upstream",
        "source, whether each capability is currently available upstream, and which",
        "local workarounds each capability gap requires.",
        "",
        "---",
        "",
        "## Pinned Production Stack",
        "",
        "| Component | Pinned Version | Status |",
        "|---|---|---|",
        "| CamillaDSP | _Gate 12 TBD_ | awaiting hardware validation |",
        "| CamillaGUI | _Gate 12 TBD_ | awaiting hardware validation |",
        "| piCorePlayer | _Gate 12 TBD_ | awaiting hardware validation |",
        "",
        "---",
        "",
        "## Source Snapshot SHAs",
        "",
        "| Source ID | Ref | SHA | Previous SHA | Fetched At |",
        "|---|---|---|---|---|",
    ]

    for src_id, info in status.get("sources", {}).items():
        sha = info.get("sha") or "—"
        prev = info.get("previous_sha") or "—"
        fetched = (info.get("fetched_at") or "—")[:19].replace("T", " ")
        sha_short = sha[:12] if sha != "—" else "—"
        prev_short = prev[:12] if prev != "—" else "—"
        lines.append(f"| `{src_id}` | — | `{sha_short}` | `{prev_short}` | {fetched} |")

    lines += [
        "",
        "---",
        "",
        "## Capability Probe Results",
        "",
    ]

    workaround_caps = capabilities.get("capabilities", [])
    all_probe_keys = set()
    for cap in workaround_caps:
        if cap.get("key"):
            all_probe_keys.add(cap["key"])

    upstream_caps = capabilities.get("upstream_capabilities", [])
    for cap in upstream_caps:
        probe_key = cap.get("probe_key")
        if probe_key:
            all_probe_keys.add(probe_key)

    if probe_results:
        branches = sorted(probe_results.keys())
        header_cols = " | ".join(f"`{b}`" for b in branches)
        sep_cols = " | ".join("---" for _ in branches)
        lines.append(f"| Capability | {header_cols} | Local Workaround |")
        lines.append(f"|---|{sep_cols}|---|")

        for probe_key in sorted(all_probe_keys):
            local_codes = []
            for cap in workaround_caps:
                if cap.get("key") == probe_key:
                    local_codes = cap.get("local_code", [])
            for cap in upstream_caps:
                if cap.get("probe_key") == probe_key or cap.get("key") == probe_key:
                    local_codes = local_codes or cap.get("local_code", [])

            branch_cols = []
            for b in branches:
                s = probe_results[b].get(probe_key, "?")
                icon = probe_status_icon(s)
                branch_cols.append(f"{icon} {s}")
            branch_str = " | ".join(branch_cols)
            lc_str = ", ".join(f"`{lc}`" for lc in local_codes[:2]) or "—"
            lines.append(f"| `{probe_key}` | {branch_str} | {lc_str} |")
    else:
        lines.append("_No probe results yet.  Run `upstream-capability-canary` workflow._")

    lines += [
        "",
        "---",
        "",
        "## Local Workarounds (Cliffhangers)",
        "",
        "| Key | File(s) | Removal Criterion | Probe |",
        "|---|---|---|---|",
    ]

    for cap in workaround_caps:
        key = cap.get("key", "?")
        lc = ", ".join(f"`{f.split('#')[0].strip()}`" for f in cap.get("local_code", [])[:2])
        removal = (cap.get("removal_when") or "").split("\n")[0].strip()[:80]
        probe_key = key
        probe_status = "⏳"
        for b, results in probe_results.items():
            s = results.get(probe_key)
            if s == "PASS":
                probe_status = "✅ PASS"
                break
            elif s == "FAIL":
                probe_status = "❌ FAIL"
        lines.append(f"| `{key}` | {lc or '—'} | {removal}… | {probe_status} |")

    lines += [
        "",
        "---",
        "",
        "## Deletion Stage Tracking (roadmap §52)",
        "",
        "| Stage | Description | Status |",
        "|---|---|---|",
        "| 1 | Stable state events → delete PollingTrigger | ⏳ |",
        "| 2 | Runtime rate override → delete config rate patch | ⏳ |",
        "| 3 | Override while inactive → delete PreviousConfig rebuild | ⏳ |",
        "| 4 | Native loopback detection → delete HCTL observer | ⏳ |",
        "| 5 | Native loopback lifecycle → delete rate_sync + reconcile.rs | ⏳ |",
        "| 6 | Complete upstream solution → delete Rust daemon | ⏳ |",
        "",
        "---",
        "",
        f"_Generated by `scripts/upstream_dashboard.py` at {generated_at}_",
    ]

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate upstream status dashboard")
    parser.add_argument("--status", default="upstream/status.json")
    parser.add_argument("--capabilities", default="upstream/capabilities.yml")
    parser.add_argument("--probes", nargs="*", default=[],
                        help="Probe result JSON files (glob output from find)")
    parser.add_argument("--output", default="upstream/status.md")
    args = parser.parse_args()

    status = load_json(args.status)
    capabilities = load_yaml(args.capabilities)
    probe_results = collect_probe_results(args.probes or [])
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    dashboard = generate_dashboard(status, capabilities, probe_results, generated_at)
    Path(args.output).write_text(dashboard)
    print(f"Dashboard written to {args.output}")


if __name__ == "__main__":
    main()
