#!/usr/bin/env python3
"""
piCoreCDSP v2 — Upstream Status Dashboard Generator (roadmap §68, Gate 14)

Reads upstream/status.json, upstream/capabilities.yml, and probe results
to generate an up-to-date upstream/status.md dashboard.

Usage:
    python3 scripts/upstream_dashboard.py \\
        --status       upstream/status.json \\
        --capabilities upstream/capabilities.yml \\
        --probes       /tmp/probe-results-*.json \\
        --output       upstream/status.md
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml


def load_json(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        return {}
    return json.loads(p.read_text())


def load_yaml(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        return {}
    return yaml.safe_load(p.read_text()) or {}


def probe_status_icon(status: str) -> str:
    return {"PASS": "✅", "FAIL": "❌", "SKIP": "⏭", "ERROR": "⚠️"}.get(status, "⏳")


def collect_probe_results(probe_files: list[str]) -> dict[str, dict[str, str]]:
    """
    Returns: {branch: {capability_key: status_str}}
    """
    results: dict[str, dict[str, str]] = {}
    for pf in probe_files:
        data = load_json(pf)
        branch = data.get("branch", "unknown")
        results[branch] = {}
        for probe in data.get("probes", []):
            cap = probe.get("capability", "?")
            status = probe.get("status", "?")
            results[branch][cap] = status
    return results


def _workaround_probe_status(
    key: str,
    probe_results: dict[str, dict[str, str]],
) -> str:
    """Return the best known probe status icon+label for a workaround key."""
    for _branch, results in probe_results.items():
        s = results.get(key)
        if s == "PASS":
            return "✅ PASS"
    for _branch, results in probe_results.items():
        s = results.get(key)
        if s == "FAIL":
            return "❌ FAIL"
    return "⏳ upstream pending"


def generate_dashboard(
    status: dict,
    capabilities: dict,
    probe_results: dict[str, dict[str, str]],
    generated_at: str,
) -> str:
    workaround_caps = capabilities.get("capabilities", [])
    upstream_caps = capabilities.get("upstream_capabilities", [])

    lines = [
        "<!-- upstream/status.md — auto-generated by upstream-sync.yml (roadmap §68). -->",
        "<!-- Do not edit manually. -->",
        "",
        "# piCoreCDSP v2 — Upstream Capability Status Dashboard",
        "",
        f"> **Auto-generated.** Last updated: `{generated_at}`",
        "",
        "This dashboard is generated by `.github/workflows/upstream-sync.yml` and",
        "`.github/workflows/upstream-capability-canary.yml`.  It summarises:",
        "- What piCoreCDSP relies on from each upstream source",
        "- Whether each capability is currently available upstream",
        "- Which local workarounds each capability gap requires",
        "- Which workarounds are candidates for deletion",
        "",
        "---",
        "",
        "## Pinned Production Stack",
        "",
        "| Component | Pinned Version | Status |",
        "|---|---|---|",
        "| CamillaDSP | _Gate 12 TBD_ | awaiting hardware validation |",
        "| CamillaGUI | _Gate 12 TBD_ | awaiting hardware validation |",
        "| piCorePlayer | _Gate 12 TBD_ | awaiting hardware validation |",
        "",
        "---",
        "",
        "## Source Snapshot SHAs",
        "",
        "| Source ID | Ref | SHA | Fetched At |",
        "|---|---|---|---|",
    ]

    for src_id, info in status.get("sources", {}).items():
        sha = info.get("sha") or "—"
        ref = info.get("ref") or "—"
        fetched = (info.get("fetched_at") or "—")[:19].replace("T", " ")
        sha_short = sha[:12] if sha != "—" else "—"
        lines.append(f"| `{src_id}` | {ref} | `{sha_short}` | {fetched} |")

    # ── Capability Probe Results ──────────────────────────────────────────────
    lines += [
        "",
        "---",
        "",
        "## Capability Probe Results",
        "",
    ]

    if probe_results:
        branches = sorted(probe_results.keys())
        # Build the set of probe keys from both workaround caps and upstream caps.
        all_probe_keys: set[str] = set()
        for cap in workaround_caps:
            if cap.get("key"):
                all_probe_keys.add(cap["key"])
        for cap in upstream_caps:
            if cap.get("probe_key"):
                all_probe_keys.add(cap["probe_key"])

        header_cols = " | ".join(f"`{b}`" for b in branches)
        sep_cols = " | ".join("---" for _ in branches)
        lines.append(f"| Capability Key | {header_cols} | Local Workaround | Removal Candidate? |")
        lines.append(f"|---|{sep_cols}|---|---|")

        for probe_key in sorted(all_probe_keys):
            local_codes: list[str] = []
            removal_hint = ""
            for cap in workaround_caps:
                if cap.get("key") == probe_key:
                    local_codes = cap.get("local_code", [])
                    removal_when = (cap.get("removal_when") or "").strip()
                    removal_hint = removal_when.split("\n")[0][:60] + "…" if removal_when else ""
            for cap in upstream_caps:
                if cap.get("probe_key") == probe_key or cap.get("key") == probe_key:
                    local_codes = local_codes or cap.get("local_code", [])

            branch_cols = []
            for b in branches:
                s = probe_results[b].get(probe_key, "?")
                icon = probe_status_icon(s)
                branch_cols.append(f"{icon} {s}")
            branch_str = " | ".join(branch_cols)
            lc_str = ", ".join(f"`{lc}`" for lc in local_codes[:2]) or "—"
            # Removal candidate: PASS on any branch = candidate for deletion.
            removal_cell = removal_hint if any(
                probe_results[b].get(probe_key) == "PASS" for b in branches
            ) else "⏳ pending"
            lines.append(f"| `{probe_key}` | {branch_str} | {lc_str} | {removal_cell} |")
    else:
        # No probe data yet — emit static pending rows from capabilities.yml.
        lines.append("| Capability Key | Probe Status | Local Workaround | Removal Candidate? |")
        lines.append("|---|---|---|---|")
        pending_rows = {
            "state_push_events": (
                "`src/rate_sync/mod.rs` PollingTrigger",
                "when PASS on 4.2+/5.x",
            ),
            "persistent_source_rate_override": (
                "`src/rate_sync/config_patch.rs`",
                "when all 6 conditions PASS",
            ),
            "native_aloop_rate_following": (
                "`src/source/alsa_loopback.rs`",
                "when all 5 conditions PASS",
            ),
            "config_revision_cas": (
                "fresh-read-before-write in reconciler",
                "when CAS/revision PASS",
            ),
            "samplerate_token_reresolution": (
                "token guard in `config_document.rs`",
                "when token-aware override PASS",
            ),
            "set_config_value": (
                "`src/rate_sync/config_patch.rs`",
                "when source_rate.override PASS",
            ),
            "camilla_v5_wire_format": (
                "`src/camilla/protocol_v4.rs`",
                "after v5 pin",
            ),
        }
        # Merge with live capabilities.yml data where available.
        for cap in workaround_caps:
            key = cap.get("key")
            if key and key not in pending_rows:
                lc = cap.get("local_code", [])
                lc_str = ", ".join(f"`{lc}`" for lc in lc[:2]) or "—"
                pending_rows[key] = (lc_str, "⏳ pending")
        for key, (workaround, removal) in pending_rows.items():
            lines.append(f"| `{key}` | ⏳ pending | {workaround} | {removal} |")

    # ── Local Workarounds Inventory ───────────────────────────────────────────
    lines += [
        "",
        "---",
        "",
        "## Local Workarounds Inventory",
        "",
        "| Workaround | File | Removal Criterion | Status |",
        "|---|---|---|---|",
    ]

    # Display name map for known workarounds.
    _display_names: dict[str, str] = {
        "persistent_source_rate_override": "ConfigPatchRateSynchronizer",
        "state_push_events": "PollingTrigger",
        "native_aloop_rate_following": "HCTL Source Observer",
        "samplerate_token_reresolution": "$samplerate$ token guard",
        "config_revision_cas": "Race mitigation (fresh reads)",
        "camilla_v5_wire_format": "protocol_v4.rs (v4 adapter)",
    }

    for cap in workaround_caps:
        key = cap.get("key", "?")
        display = _display_names.get(key, key)
        lc_list = cap.get("local_code", [])
        file_cell = f"`{lc_list[0].split('#')[0].strip()}`" if lc_list else "—"
        removal_when = (cap.get("removal_when") or "").strip()
        # First line of removal_when, capped at 60 chars.
        removal_summary = removal_when.split("\n")[0].strip()[:60]
        first_line = removal_when.split("\n")[0].strip()
        if len(first_line) > 60:
            removal_summary += "…"
        probe_status_str = _workaround_probe_status(key, probe_results)
        lines.append(f"| {display} | {file_cell} | {removal_summary} | {probe_status_str} |")

    # ── Deletion Stage Tracking ───────────────────────────────────────────────
    lines += [
        "",
        "---",
        "",
        "## Deletion Stage Tracking (roadmap §52)",
        "",
        "| Stage | Description | Upstream Gate | Status |",
        "|---|---|---|---|",
    ]

    stage_rows = [
        ("1", "Stable state events → delete PollingTrigger",
         "`state_push_events` PASS on prod",
         _workaround_probe_status("state_push_events", probe_results)),
        ("2", "Runtime rate override → delete config rate patch",
         "`persistent_source_rate_override` PASS",
         _workaround_probe_status("persistent_source_rate_override", probe_results)),
        ("3", "Override while inactive → delete PreviousConfig rebuild",
         "all 6 conditions PASS",
         _workaround_probe_status("persistent_source_rate_override", probe_results)),
        ("4", "Native loopback rate detection → delete Rust HCTL observer",
         "`native_aloop_rate_following` PASS",
         _workaround_probe_status("native_aloop_rate_following", probe_results)),
        ("5", "Native loopback lifecycle → delete rate_sync + most of reconcile.rs",
         "all 5 conditions PASS",
         _workaround_probe_status("native_aloop_rate_following", probe_results)),
        ("6", "Complete upstream solution → delete Rust daemon",
         "full CamillaDSP native support",
         "⏳"),
    ]
    for stage, desc, gate, stage_status in stage_rows:
        lines.append(f"| {stage} | {desc} | {gate} | {stage_status} |")

    lines += [
        "",
        "---",
        "",
        "_Populate this dashboard by running the `upstream-sync` workflow._",
        "",
        f"_Generated by `scripts/upstream_dashboard.py` at {generated_at}_",
    ]

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate upstream status dashboard")
    parser.add_argument("--status", default="upstream/status.json")
    parser.add_argument("--capabilities", default="upstream/capabilities.yml")
    parser.add_argument("--probes", nargs="*", default=[],
                        help="Probe result JSON files (glob output from find)")
    parser.add_argument("--output", default="upstream/status.md")
    args = parser.parse_args()

    status = load_json(args.status)
    capabilities = load_yaml(args.capabilities)
    probe_results = collect_probe_results(args.probes or [])
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    dashboard = generate_dashboard(status, capabilities, probe_results, generated_at)
    Path(args.output).write_text(dashboard)
    print(f"Dashboard written to {args.output}")


if __name__ == "__main__":
    main()
